services:
  master-server:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "8080:8080"
    environment:
      - TG_ADMIN_ID=${TG_ADMIN_ID}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
    depends_on:
      - postgres
    networks:
      - vpn-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: novich
      POSTGRES_PASSWORD: novich
      POSTGRES_DB: vpndb
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vpn-network

volumes:
  postgres_data:

networks:
  vpn-network:
    driver: bridge