services:
  master-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - TG_ADMIN_ID=${TG_ADMIN_ID}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - vpn-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: novich
      POSTGRES_PASSWORD: novich
      POSTGRES_DB: vpndb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema:/docker-entrypoint-initdb.d
    networks:
      - vpn-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U novich -d vpndb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  vpn-network:
    driver: bridge